FROM node:18-alpine AS development

WORKDIR /demo/src/app

COPY package*.json ./

RUN yarn install

RUN yarn install --only=development

COPY  . .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start:dev"]